---
language: python

python:
  - "2.7"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  
script:
  - coverage run `which nosetests` -c nose.cfg 
  - coverage report --skip-covered

