---
language: python
python:
  - "2.7"
# command to install dependencies
branches:
  only:
    -develop
    -master
before_install:
  - git clone https://github.com/kbase/kb_sdk.git
install:
  - pip install -r requirements.txt
# command to run tests
script: make && make test
